from collections.abc import Iterable
from typing import Any, TypeVar

import numpy as np
from numpy.typing import NDArray

from .utils import FloatArray, NumericArray

_T = TypeVar("_T", bound=NumericArray)
_F = TypeVar("_F", bound=FloatArray)

def allnan(arrays, /, *, axis: int | tuple[int, ...] | None = None): ...
def anynan(arrays, /, *, axis: int | tuple[int, ...] | None = None): ...
def nancount(arrays, /, *, axis: int | tuple[int, ...] | None = None): ...
def nansum(arrays, /, *, axis: int | tuple[int, ...] | None = None): ...
def nanmean(arrays, /, *, axis: int | tuple[int, ...] | None = None): ...
def nanvar(arrays, /, *, ddof: int = 1, axis: int | tuple[int, ...] | None = None): ...
def nanstd(arrays, /, *, ddof: int = 1, axis: int | tuple[int, ...] | None = None): ...
def nanargmax(arr: NDArray[Any], *args, axis: tuple[int, ...] | int | None = None): ...
def nanargmin(arr: NDArray[Any], *args, axis: tuple[int, ...] | int | None = None): ...
def nanmax(arr: NDArray[Any], *args, axis: tuple[int, ...] | int | None = None): ...
def nanmin(arr: NDArray[Any], *args, axis: tuple[int, ...] | int | None = None): ...
def nanquantile(
    a: NDArray[np.float64],
    quantiles: float | Iterable[float],
    axis: int | tuple[int, ...] | None = None,
    **kwargs,
) -> NDArray[np.float64]: ...
def nanmedian(
    a: NDArray[np.float64], *, axis: int | tuple[int, ...] | None = None, **kwargs
) -> NDArray[np.float64]: ...
def bfill(
    arr: _T,
    *,
    limit: int | None = None,
    axis: int = -1,
) -> _T: ...
def ffill(
    arr: _T,
    *,
    limit: int | None = None,
    axis: int = -1,
) -> _T: ...

# `(..., vars, obs) -> (..., vars, vars)`: the trailing axis is reduced away and a
# second `vars` axis takes its place, so ndim and dtype both carry through from the
# input. There is no `axis` parameter, so unlike the aggregations above the return
# does not depend on how the call is made.
def nancovmatrix(a: _F, **kwargs) -> _F: ...
def nancorrmatrix(a: _F, **kwargs) -> _F: ...

count = nancount
